### ISSUE TITLE
clipcat-menu doesn't insert content to clipboard in X11

### ISSUE THREAD

**Issue by wrvsrx** [Icelk/clipcat#14]
I'll find why later, now I'm short of time.

**Comment by Icelk** [comment]
I saw your commit and did something similar. Does it work now?
Seems I overlooked pasting when building the multiple-backends code.

**Comment by wrvsrx** [comment]
Sadly not. Paste doesn't work not only becase build flags but also because old clipcat's x11 pasting relies on a wrong behavior of old version of x11-clipboard:

When the clipboard object is created, a corresponding thread will be created. Only when this thread exists can it process the paste request from x11 normally.

Normally, we should create a new clipboard object and then access the X11 clipboard through it all the time. But in clipcat, we will create a new clipboard object https://github.com/Icelk/clipcat/blob/bcda4e4e62e58e9240ad94e6adf6d6667b5c21c0/src/manager.rs#L272 every time we need paste, and the object will be destroyed after the paste. However , in the previous implementation of x11-clipboard, the thread was not destroyed after the clipboard object was destroyed (of course this is a wrong behavior). So clipcat can still paste normally, but at the cost of each paste will be an extra The destroyed thread.

Later this problem was fixed in upstream (https://github.com/quininer/x11-clipboard/commit/267572e1a95fa59e3f326abd1269a3ba909a0254), the thread will be destroyed correctly, so our X11 paste will not work.

**Comment by wrvsrx** [comment]
That's why in my commit (https://github.com/wrvsrx/clipcat/blob/55b3216f39a53a9c6a9c9cd2821712687c224ada/src/manager.rs#L9) I create a single clipboard instance and use it for all paste operation.

**Comment by wrvsrx** [comment]
> So clipcat can still paste normally, but at the cost of each paste will be an extra The destroyed thread.

This is the cost https://github.com/xrelkd/clipcat/issues/24

**Comment by Icelk** [comment]
Smart. So our implementation doesn't work because when we drop the `x11_clipboard::Clipboard`, the pasting stops?

**Comment by wrvsrx** [comment]
Yes.

**Comment by Icelk** [comment]
I modified the implementation to do what you described. Does it function correctly now?

**Comment by wrvsrx** [comment]
Thank you! It works now.

**Comment by Icelk** [comment]
Thank you for testing and writing the fix!
