### ISSUE TITLE
Feature request: Add image support

### ISSUE THREAD

**Issue by benedikt-bartscher** [Icelk/clipcat#17]
First of all, thank you @Icelk and @wrvsrx for continuing @xrelkd's work!
I am currently using greenclip which allows storing small images. It would be awesome if clipcat could support images too, as i prefer a client-server architecture to sync my clipboard across devices.

**Comment by Icelk** [comment]
Thank you for those kind words.

At least using Wayland, that should work. The internal representation of copied data and the storage format will have to be changed, but that is manageable. I'm however uncertain if we can copy images with the `x11_clipboard` crate. @wrvsrx do you have any comments?

**Comment by wrvsrx** [comment]
Sadly not. If we want to get image data, we might need to change to another crate: ar-board.

However, it seems that this crate doesn't implement listener to clipboard .

**Comment by benedikt-bartscher** [comment]
Related issue in x11-clipboard: https://github.com/quininer/x11-clipboard/issues/18

**Comment by benedikt-bartscher** [comment]
And here is a pretty interesting blog post about X11 clipboards and rust: https://medium.com/journey-to-rust/working-with-clipboard-b4564b906d46
The author finally uses a somehow ugly solution which just invokes xclip but it works: https://github.com/dmac/clipboard/blob/master/src/clipboard_linux.rs

**Comment by wrvsrx** [comment]
In fact, we can use arboard to read x11 clipboard and write some code to monitor clipboard change in x11.

Arboard can also read clipboard from Wayland, but I don't know if it is easy to watch clipboard change in Wayland.

**Comment by Icelk** [comment]
So do you suggest using our listener implementation and loading images with arboard? Or does our implementation not emit image copy events?

Right now, we simply poll the Wayland clipboard and compare with the previously known value. It's actually quite bad. But from my initial research, there isn't a better way.

**Comment by Icelk** [comment]
I looked at the implementation in arboard (https://docs.rs/arboard/latest/src/arboard/platform/linux/x11.rs.html), and the image part doesn't seem too complicated. Should you or I PR your x11_clipboard fork to add image support? It seems like copying is done over PNG, but we shouldn't need to decode the image.

What do you both think should appear in clipcat-menu when an image is available? Maybe the executable that we copied from? (If that's available)

**Comment by benedikt-bartscher** [comment]
Showing a thumbnail of the image would be really cool. Maybe we could just use rofi's icon support which was added in 1.7.0? I have not played with it yet but i will try later.

**Comment by Icelk** [comment]
I agree. The default view is a list. That would make the images very small. Should we provide an alternative grid view for pasting images?

We'll also need the `image` library to decode the PNG & resize it then

**Comment by wrvsrx** [comment]
> So do you suggest using our listener implementation and loading images with arboard? Or does our implementation not emit image copy events?

Yes. Implementing a listener is not hard, at least in x11.

> Right now, we simply poll the Wayland clipboard and compare with the previously known value. It's actually quite bad. But from my initial research, there isn't a better way.

In https://github.com/bugaevc/wl-clipboard, they implement a `--watch` option. Therefore it's possible to watch clipboard event in wayland, maybe we need to read the code.

**Comment by Icelk** [comment]
I opened #19 for watch support.

**Comment by Icelk** [comment]
> Yes. Implementing a listener is not hard, at least in x11

So does it support image events? I would guess they are the same event but with different data?

Would you, @wrvsrx mind adding image support?

**Comment by wrvsrx** [comment]
> So does it support image events?

Yes. It's almost same.

> Would you, @wrvsrx mind adding image support?

Currently I'm short of time. Maybe later.

**Comment by wrvsrx** [comment]
@benedikt-bartscher The [original repo](https://github.com/xrelkd/clipcat) has started updating again, and it support image copy/paste now. Maybe you can check it.

**Comment by benedikt-bartscher** [comment]
Thank you very much @wrvsrx for keeping me up2date!
