### ISSUE TITLE
Build fails in nix-shell

### ISSUE THREAD

**Issue by magnetophon** [Icelk/clipcat#2]
When I try to build this via ``nix-shell``, the last few lines I get are:

```
   Compiling clipcat v0.5.0 (/home/bart/source/clipcat-Icelk)
   Compiling tracing-serde v0.1.3
   Compiling serde_with v1.14.0
   Compiling bincode v1.3.3
   Compiling toml v0.5.10
   Compiling tracing-subscriber v0.2.25
   Compiling hyper v0.14.23
   Compiling tracing-journald v0.1.0
   Compiling tonic v0.4.3
error[E0063]: missing field `filter_min_size` in initializer of `ClipboardMonitorOptions`
  --> src/bin/clipcat-notify/main.rs:71:28
   |
71 |         let monitor_opts = ClipboardMonitorOptions {
   |                            ^^^^^^^^^^^^^^^^^^^^^^^ missing `filter_min_size`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `clipcat` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clipcat v0.5.0 (/home/bart/source/clipcat-Icelk)`, intermediate artifacts can be found at `/home/bart/source/clipcat-Icelk/target`
```

The commands I'm running:

```
cd $this-repo
nix-shell
cargo install --path . --features clipcatd,clipcat-menu,clipcatctl,clipcat-notify
```

The upstream repo builds and runs just fine.

**Comment by Icelk** [comment]
This is now resolved since 61be28e.
Thanks for bringing it to my attention!

**Comment by magnetophon** [comment]
@Icelk Thanks!
Unfortunately, I get:

```
nix-shell
error: cannot evaluate a function that has an argument without a value ('mkShell')

       Nix attempted to evaluate a function as a top level expression; in
       this case it must have its arguments supplied either by default
       values, or passed explicitly with '--arg' or '--argstr'. See
       https://nixos.org/manual/nix/stable/expressions/language-constructs.html#functions.

       at /home/bart/source/clipcat-Icelk/shell.nix:1:3:

            1| { mkShell, clipcat }:
             |   ^
            2|
```

**Comment by Icelk** [comment]
That issue is probably due to #5. Try checking out 416136 and compiling there.
@wrvsrx Can you help with this?

**Comment by wrvsrx** [comment]
It's another problem. I only consider use it with flake, therefore only direnv works while nix-shell works bad. I'll make a PR later.

**Comment by Icelk** [comment]
Thanks!
Is there any advantage with supporting `nix-shell`?

**Comment by wrvsrx** [comment]
`nix-shell` is the legacy method in nix to build development environment. It use `shell.nix` to get env information.

It **might** be replaced in the future by flake mode (store all information in flake.nix and use `nix develop` or `direnv`'s flake mode to activate development environment) (I use "might" because `nix develop` is still an experimental feature, although a lot of people have changed to use it.

I think support `shell.nix` is still worthwhile, but I can't ensure it always work since I don't use it frequently.

**Comment by Icelk** [comment]
Right. Do it if you have the time :)

**Comment by wrvsrx** [comment]
Can you try if `nix-shell` works with #10? @magnetophon 

It should work now, I have tested it. But I'm not familiar with `nix-shell`.

**Comment by magnetophon** [comment]
> Can you try if `nix-shell` works with #10? @magnetophon

It does!
Thank you!
