### ISSUE TITLE
CI workflow doesn't test the case where "wayland" feature is disabled

### ISSUE THREAD

**Issue by wrvsrx** [Icelk/clipcat#6]
Since CI workflow enable all features, code for X11 is ignored in CI workflow. You can check that current repo HEAD (https://github.com/Icelk/clipcat/tree/416136248c882fffb66dcaad72f913d53dfaafd5) doesn't compile for X11.

I'll make a PR to fix these problems.

**Comment by wrvsrx** [comment]
- Fix the compile problem by #7 
- Fix the CI by #8

**Comment by Icelk** [comment]
This should be fixed, as #8 is merged!
Thanks!
